inherit_gem:
  rubocop-govuk:
    - config/default.yml

# The old-style hash syntax is often used in capistrano scripts. New hash-syntax
# is not more readable here, so allow both styles.
Style/HashSyntax:
  Enabled: false

# People understand heredoc EOF/EOS syntax as it is.
Naming/HeredocDelimiterNaming:
  Enabled: false

# It's complaining about `recipes` files. These are deployment files
# which would take time to fix. Maybe later?
Metrics/BlockLength:
  Enabled: false
